SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tag](
	[tagId] [bigint] NOT NULL,
	[tagFree] [bit] NULL,
	[tagKey] [varchar](45) NULL,
	[orderID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tag] ADD PRIMARY KEY CLUSTERED 
(
	[tagId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tag] ADD  DEFAULT (NULL) FOR [tagKey]
GO
